#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ant
Version  : 1.9.1
Release  : 12
URL      : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.1/ant-1.9.1.jar
Source0  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.1/ant-1.9.1.jar
Source1  : https://repo.maven.apache.org/maven2/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4-sources.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4.jar
Source3  : https://repo.maven.apache.org/maven2/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4.pom
Source4  : https://repo.maven.apache.org/maven2/org/apache/ant/ant-parent/1.9.4/ant-parent-1.9.4.pom
Source5  : https://repo.maven.apache.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4-sources.jar
Source6  : https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.jar
Source7  : https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.pom
Source8  : https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.8.1/ant-parent-1.8.1.pom
Source9  : https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.8.2/ant-parent-1.8.2.pom
Source10  : https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.9.1/ant-parent-1.9.1.pom
Source11  : https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.9.3/ant-parent-1.9.3.pom
Source12  : https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.9.4/ant-parent-1.9.4.pom
Source13  : https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.9.6/ant-parent-1.9.6.pom
Source14  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.8.1/ant-1.8.1.jar
Source15  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.8.1/ant-1.8.1.pom
Source16  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.jar
Source17  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.pom
Source18  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.1/ant-1.9.1.pom
Source19  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.3/ant-1.9.3.jar
Source20  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.3/ant-1.9.3.pom
Source21  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.jar
Source22  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.pom
Source23  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.6/ant-1.9.6.jar
Source24  : https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.6/ant-1.9.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-ant-data = %{version}-%{release}
Requires: mvn-ant-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-ant package.
Group: Data

%description data
data components for the mvn-ant package.


%package license
Summary: license components for the mvn-ant package.
Group: Default

%description license
license components for the mvn-ant package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-ant
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-ant/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.1/ant-1.9.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.4
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.4/ant-parent-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-launcher/1.9.6
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-launcher/1.9.6
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.8.1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.8.1/ant-parent-1.8.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.8.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.8.2/ant-parent-1.8.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.1/ant-parent-1.9.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.3
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.3/ant-parent-1.9.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.4
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.4/ant-parent-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.6
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.6/ant-parent-1.9.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.1
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.1/ant-1.8.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.1
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.1/ant-1.8.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.2
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.2
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.1
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.1/ant-1.9.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.3
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.3/ant-1.9.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.3
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.3/ant-1.9.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.6
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.6/ant-1.9.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.6
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.6/ant-1.9.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4-sources.jar
/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/ant/ant-junit/1.9.4/ant-junit-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.jar
/usr/share/java/.m2/repository/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.pom
/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.8.1/ant-parent-1.8.1.pom
/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.8.2/ant-parent-1.8.2.pom
/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.1/ant-parent-1.9.1.pom
/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.3/ant-parent-1.9.3.pom
/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.4/ant-parent-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/ant/ant-parent/1.9.6/ant-parent-1.9.6.pom
/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.1/ant-1.8.1.jar
/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.1/ant-1.8.1.pom
/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.jar
/usr/share/java/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.pom
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.1/ant-1.9.1.jar
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.1/ant-1.9.1.pom
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.3/ant-1.9.3.jar
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.3/ant-1.9.3.pom
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4-sources.jar
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.6/ant-1.9.6.jar
/usr/share/java/.m2/repository/org/apache/ant/ant/1.9.6/ant-1.9.6.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-ant/LICENSE.txt
